# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build docker image
      run: docker build -f Cattobot/Dockerfile -t lanternmouse/cattobot:latest .
      
  deploy:
    needs: build
    runs-on: self-hosted
    env:
      TOKEN: ${{ secrets.TOKEN }}
      KINOPOISK_TOKEN: ${{ secrets.KINOPOISK_TOKEN }}
      CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}

    steps:
      - uses: actions/checkout@v4
      - name: Remove old container
        run: |
          docker stop cattobot-container || true
          docker rm cattobot-container || true
      - name: Run new container
        run: |
          echo "${CONNECTION_STRING}"
          docker run -d \
            --name cattobot-container \
            --restart unless-stopped \
            -e Cattobot__Token="${TOKEN}" \
            -e Kinopoisk__Token="${KINOPOISK_TOKEN}" \
            -e ConnectionStrings__Default="${CONNECTION_STRING}" \
            lanternmouse/cattobot:latest
      - name: Cleanup
        run: docker image prune -f
