# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build docker image
      run: docker build -f Cattobot/Dockerfile -t lanternmouse/cattobot:latest .
      
  deploy:
    needs: build
    runs-on: self-hosted
    env:
      Cattobot__Token: ${{ secrets.CATTOBOT__TOKEN }}
      Kinopoisk__Token: ${{ secrets.KINOPOISK__TOKEN }}
      ConnectionStrings__Default: ${{ secrets.CONNECTIONSTRINGS__DEFAULT }}

    steps:
      - uses: actions/checkout@v4
      - name: Remove old container
        run: |
          docker stop cattobot-container || true
          docker rm cattobot-container || true
      - name: Run new container
        run: |
          echo "$ConnectionStrings__Default"
          docker run -d \
            --name cattobot-container \
            --restart unless-stopped \
            -e Cattobot__Token="$Cattobot__Token" \
            -e Kinopoisk__Token="$Kinopoisk__Token" \
            -e ConnectionStrings__Default="$ConnectionStrings__Default" \
            lanternmouse/cattobot:latest
      - name: Cleanup
        run: docker image prune -f
