# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build docker image
      run: docker build -f Cattobot/Dockerfile -t lanternmouse/cattobot:latest .
      
  deploy:
    needs: build
    runs-on: self-hosted
    env:
      Cattobot__Token: ${{ secrets.Cattobot__Token }}
      Kinopoisk__Token: ${{ secrets.Kinopoisk__Token }}
      ConnectionStrings__Default: ${{ secrets.ConnectionStrings__Default }}

    steps:
      - uses: actions/checkout@v4
      - name: Remove old container
        run: |
          docker stop cattobot-container || true
          docker rm cattobot-container || true
      - name: Run new container
        run: |
          docker run -d \
            --name cattobot-container \
            --restart unless-stopped \
            lanternmouse/cattobot:latest
      - name: Cleanup
        run: docker image prune -f
