# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      run: |
        docker build -f Cattobot/Dockerfile -t lanternmouse/cattobot:latest -t lanternmouse/cattobot:${{ github.sha }} .
        docker push lanternmouse/cattobot:latest
        docker push lanternmouse/cattobot:${{ github.sha }}
      
  deploy:
    
    needs: build
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull latest image
        run: docker pull lanternmouse/cattobot:latest
        
      - name: Remove old container
        run: |
          docker stop cattobot-container || true
          docker rm cattobot-container || true
          
      - name: Run new container
        env:
          TOKEN: ${{ secrets.TOKEN }}
          KINOPOISK_TOKEN: ${{ secrets.KINOPOISK_TOKEN }}
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
        run: |
          echo "${CONNECTION_STRING}"
          docker run -d \
            --name cattobot-container \
            --network mynet \
            --restart unless-stopped \
            -e Cattobot__Token="${TOKEN}" \
            -e Kinopoisk__Token="${KINOPOISK_TOKEN}" \
            -e ConnectionStrings__Default="${CONNECTION_STRING}" \
            --add-host=host.docker.internal:host-gateway \
            lanternmouse/cattobot:latest
          
      - name: Cleanup
        run: docker image prune -f